version: '3.3'

services:
  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbmaster
      POSTGRES_DB: postgres
    volumes:
      - /var/create_database.sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - network-grpc

  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - 8080:80
    depends_on:
      - pgsql
    networks:
      - network-grpc

  net-grpc:
    environment:
      GO_ENV: development
    build: 
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - pgsql
    networks:
      - network-grpc

  net-api:
    environment:
      GO_ENV: development
    build:
      context: ../net-api/.
      dockerfile: ../net-api/Dockerfile
    ports:
      - 9191:9191
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - net-grpc
    networks:
      - network-grpc

networks:
  network-grpc:
    driver: bridge