// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: private-service.proto

package private_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDisplayBooks - Returns one random book and the latest book displayed
// if it's the first call of the day, the last_book will be empty
type GetDisplayBooksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RandomBook *Book `protobuf:"bytes,1,opt,name=random_book,proto3" json:"random_book,omitempty"`
	LastBook   *Book `protobuf:"bytes,2,opt,name=last_book,proto3,oneof" json:"last_book,omitempty"`
}

func (x *GetDisplayBooksResponse) Reset() {
	*x = GetDisplayBooksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDisplayBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisplayBooksResponse) ProtoMessage() {}

func (x *GetDisplayBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisplayBooksResponse.ProtoReflect.Descriptor instead.
func (*GetDisplayBooksResponse) Descriptor() ([]byte, []int) {
	return file_private_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDisplayBooksResponse) GetRandomBook() *Book {
	if x != nil {
		return x.RandomBook
	}
	return nil
}

func (x *GetDisplayBooksResponse) GetLastBook() *Book {
	if x != nil {
		return x.LastBook
	}
	return nil
}

// GetBookRandomRequest represents the get book details request
type GetBookRandomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=api_key,proto3" json:"api_key,omitempty"`
}

func (x *GetBookRandomRequest) Reset() {
	*x = GetBookRandomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookRandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRandomRequest) ProtoMessage() {}

func (x *GetBookRandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRandomRequest.ProtoReflect.Descriptor instead.
func (*GetBookRandomRequest) Descriptor() ([]byte, []int) {
	return file_private_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookRandomRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// GetBookDetailsRequest represents the get book details request
type GetBookDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=api_key,proto3" json:"api_key,omitempty"`
	BookId string `protobuf:"bytes,2,opt,name=book_id,proto3" json:"book_id,omitempty"`
}

func (x *GetBookDetailsRequest) Reset() {
	*x = GetBookDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookDetailsRequest) ProtoMessage() {}

func (x *GetBookDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetBookDetailsRequest) Descriptor() ([]byte, []int) {
	return file_private_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookDetailsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetBookDetailsRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

// GetBookDetailsRequest represents the get book details request
type GetBookDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId string `protobuf:"bytes,1,opt,name=book_id,proto3" json:"book_id,omitempty"`
	Book   *Book  `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *GetBookDetailsResponse) Reset() {
	*x = GetBookDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookDetailsResponse) ProtoMessage() {}

func (x *GetBookDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetBookDetailsResponse) Descriptor() ([]byte, []int) {
	return file_private_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookDetailsResponse) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *GetBookDetailsResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

// Book
// Json Example:
//
//	{
//	 id: "asdfasdfasdf"
//	 "title": "Tractor Mechanics",
//	 "authors": [
//	   "Roger Welsch"
//	 ],
//	 "subtitle": "A Catalog Performance Objectives, Criterion-referenced Measures, and Performance Guides for Tractor Mechanics",
//	 "publishedDate": "1976",
//	 "pageCount": 240,
//	 "printType": "BOOK",
//	 "imageLinks": {
//	   "smallThumbnail": "http://books.google.com/books/content?id=ohlJn7ehfvMC&printsec=frontcover&img=1&zoom=5&source=gbs_api",
//	   "thumbnail": "http://books.google.com/books/content?id=ohlJn7ehfvMC&printsec=frontcover&img=1&zoom=10&source=gbs_api"
//	 },
//	 "language": "en"
//	}
type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Authors       []string        `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"` // Can be empty string array
	ImageLinks    *BookImageLinks `protobuf:"bytes,7,opt,name=image_links,proto3" json:"image_links,omitempty"`
	PrintType     string          `protobuf:"bytes,6,opt,name=print_type,proto3" json:"print_type,omitempty"`
	Language      string          `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	PublishedDate *int32          `protobuf:"varint,4,opt,name=published_date,proto3,oneof" json:"published_date,omitempty"`
	PageCount     *int32          `protobuf:"varint,5,opt,name=page_count,proto3,oneof" json:"page_count,omitempty"`
	Description   *string         `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_private_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_private_service_proto_rawDescGZIP(), []int{4}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Book) GetImageLinks() *BookImageLinks {
	if x != nil {
		return x.ImageLinks
	}
	return nil
}

func (x *Book) GetPrintType() string {
	if x != nil {
		return x.PrintType
	}
	return ""
}

func (x *Book) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Book) GetPublishedDate() int32 {
	if x != nil && x.PublishedDate != nil {
		return *x.PublishedDate
	}
	return 0
}

func (x *Book) GetPageCount() int32 {
	if x != nil && x.PageCount != nil {
		return *x.PageCount
	}
	return 0
}

func (x *Book) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type BookImageLinks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmallThumbnail string `protobuf:"bytes,1,opt,name=small_thumbnail,proto3" json:"small_thumbnail,omitempty"`
	Thumbnail      string `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
}

func (x *BookImageLinks) Reset() {
	*x = BookImageLinks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookImageLinks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookImageLinks) ProtoMessage() {}

func (x *BookImageLinks) ProtoReflect() protoreflect.Message {
	mi := &file_private_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookImageLinks.ProtoReflect.Descriptor instead.
func (*BookImageLinks) Descriptor() ([]byte, []int) {
	return file_private_service_proto_rawDescGZIP(), []int{5}
}

func (x *BookImageLinks) GetSmallThumbnail() string {
	if x != nil {
		return x.SmallThumbnail
	}
	return ""
}

func (x *BookImageLinks) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

var File_private_service_proto protoreflect.FileDescriptor

var file_private_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x62, 0x6f,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x0b,
	0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x37, 0x0a, 0x09, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x62, 0x6f, 0x6f,
	0x6b, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x62, 0x6f,
	0x6f, 0x6b, 0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70,
	0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x69,
	0x5f, 0x6b, 0x65, 0x79, 0x22, 0x4b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69,
	0x64, 0x22, 0x5c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f,
	0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22,
	0xef, 0x02, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x0b, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42,
	0x11, 0x0a, 0x0f, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x58, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69,
	0x6e, 0x6b, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x6d,
	0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x32, 0xd6, 0x01, 0x0a, 0x12,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x60, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x30, 0x01, 0x12, 0x5e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_private_service_proto_rawDescOnce sync.Once
	file_private_service_proto_rawDescData = file_private_service_proto_rawDesc
)

func file_private_service_proto_rawDescGZIP() []byte {
	file_private_service_proto_rawDescOnce.Do(func() {
		file_private_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_private_service_proto_rawDescData)
	})
	return file_private_service_proto_rawDescData
}

var file_private_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_private_service_proto_goTypes = []interface{}{
	(*GetDisplayBooksResponse)(nil), // 0: privateService.GetDisplayBooksResponse
	(*GetBookRandomRequest)(nil),    // 1: privateService.GetBookRandomRequest
	(*GetBookDetailsRequest)(nil),   // 2: privateService.GetBookDetailsRequest
	(*GetBookDetailsResponse)(nil),  // 3: privateService.GetBookDetailsResponse
	(*Book)(nil),                    // 4: privateService.Book
	(*BookImageLinks)(nil),          // 5: privateService.BookImageLinks
}
var file_private_service_proto_depIdxs = []int32{
	4, // 0: privateService.GetDisplayBooksResponse.random_book:type_name -> privateService.Book
	4, // 1: privateService.GetDisplayBooksResponse.last_book:type_name -> privateService.Book
	4, // 2: privateService.GetBookDetailsResponse.book:type_name -> privateService.Book
	5, // 3: privateService.Book.image_links:type_name -> privateService.BookImageLinks
	1, // 4: privateService.PrivateBookService.GetRandomBook:input_type -> privateService.GetBookRandomRequest
	2, // 5: privateService.PrivateBookService.GetBookDetail:input_type -> privateService.GetBookDetailsRequest
	0, // 6: privateService.PrivateBookService.GetRandomBook:output_type -> privateService.GetDisplayBooksResponse
	3, // 7: privateService.PrivateBookService.GetBookDetail:output_type -> privateService.GetBookDetailsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_private_service_proto_init() }
func file_private_service_proto_init() {
	if File_private_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_private_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDisplayBooksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookRandomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookImageLinks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_private_service_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_private_service_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_private_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_private_service_proto_goTypes,
		DependencyIndexes: file_private_service_proto_depIdxs,
		MessageInfos:      file_private_service_proto_msgTypes,
	}.Build()
	File_private_service_proto = out.File
	file_private_service_proto_rawDesc = nil
	file_private_service_proto_goTypes = nil
	file_private_service_proto_depIdxs = nil
}
